linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused

run:
  timeout: 10m

issues:
  exclude-use-default: false
  max-same-issues: 0
